### ISSUE TITLE
Feature Request: Allow a header row

### ISSUE THREAD

**Issue by pekempy** [tgel0/crssnt#1]
It would be handy to be able to have a header row to specify which columns go to which field in the RSS feed.
e.g. 
A1: title - All under this go into Title
B1: link - All in this column go to link
C1: description
D1: pubdate
E1: author
F1: guid

This would give more flexibility for crssnt and prevent errors when dates are detected in description/title column

**Comment by tgel0** [comment]
I like this idea! Adding it to my list.

**Comment by amblerkr** [comment]
Good idea.
G1: Thumbnail OR Image  
Please make an image row, too.

**Comment by tgel0** [comment]
I added a new commit (https://github.com/tgel0/crssnt/commit/b0ef8210e8fc955fb133707186879a0b68f8449a) which generates the RSS feed elements based on the header row from the Google Sheet. To try out this new feature just add the `&mode=manual` parameter to the crssnt feed URL.

Example based on the 'movie_manual' sheet from [this Google Sheet](https://docs.google.com/spreadsheets/d/1sV87k2cBmxFld7r4JI8LIBI7-KUxgifr1aszdV3xu08/edit?usp=sharing):

`https://crssnt.com/preview?id=1sV87k2cBmxFld7r4JI8LIBI7-KUxgifr1aszdV3xu08&name=movie_manual&mode=manual`

Would be great if you could try it out and provide feedback.

**Comment by pekempy** [comment]
Hey @tgel0  - Apologies been busy with other projects for a while.

Appears to be working perfectly! I was having an issue at first but changing `date` to `pubDate` as the title in google sheets has done it :)
Thank you!

**Comment by amblerkr** [comment]
> I added a new commit ([b0ef821](https://github.com/tgel0/crssnt/commit/b0ef8210e8fc955fb133707186879a0b68f8449a)) which generates the RSS feed elements based on the header row from the Google Sheet. To try out this new feature just add the `&mode=manual` parameter to the crssnt feed URL.
> 
> Example based on the 'movie_manual' sheet from [this Google Sheet](https://docs.google.com/spreadsheets/d/1sV87k2cBmxFld7r4JI8LIBI7-KUxgifr1aszdV3xu08/edit?usp=sharing):
> 
> `https://crssnt.com/preview?id=1sV87k2cBmxFld7r4JI8LIBI7-KUxgifr1aszdV3xu08&name=movie_manual&mode=manual`
> 
> Would be great if you could try it out and provide feedback.

It seems to work only in lowercase letters. Can you make both lower and upper case letters work?
`Title`, `Description`, `Link`, `Image`, `PubDate`, `Author`

If possible, can you add Korean?
`Title` = `제목`
`Description` = `내용`
`Link` = `링크`
`Image` = `이미지`
`PubDate` = `날짜` OR `작성일`
`Author` = `저자` OR `작성자` OR `글쓴이`

And the current `image` doesn't seem to be working.
I think it would be good to make `PubDate` work even if write `Date`.
