### ISSUE TITLE
years in titles causing title and date fields to get mixed up

### ISSUE THREAD

**Issue by denisenadal** [tgel0/crssnt#2]
I've been trying to figure  out why some items in my RSS Feed have titles that look like dates, when the titles look like normal strings in my google sheet. I think titles that have years in them are being mistaken for dates and are pulled out of the row's value array. When this happens, whatever ends up being the first value in the array (in my case, a date field) after the title is removed is used as the RSS item's title.

You can see my RSS feed here: https://crssnt.com/preview/https:/docs.google.com/spreadsheets/d/160ITxx-DvIgBRGarDp40fkRSo0Y77zDyls9fhgEXiRc/edit?usp=sharing 

Would it be possible to pull the title field out of the array before searching for the date and url fields, so that it doesn't get confused?

Something like 
```
if(value.length > 0) {      
      let title = value.shift();

      let url = value.find(s => s.startsWith('http'));
      let date = value.find(s => Date.parse(s));
```
Thanks!

**Comment by tgel0** [comment]
Thanks for submitting this issue! I've encountered it myself as well. 

Your solution sounds simple enough - I will give it a try later and report back! 🙂

**Comment by tgel0** [comment]
Just deployed a new commit with your suggestion as well as an improved way of checking for date fields.

Would be great if you could test it once and provide feedback. 🙏

https://github.com/tgel0/crssnt/commit/4138916aac4a454185fecfea69b981598618d992

**Comment by denisenadal** [comment]
Yes, all the titles are showing up correctly on my feed now: https://crssnt.com/preview/https:/docs.google.com/spreadsheets/d/160ITxx-DvIgBRGarDp40fkRSo0Y77zDyls9fhgEXiRc/edit?usp=sharing 

and it also fixed the issue where some of them were showing inaccurate dates! 

Thank you so much!
