### ISSUE TITLE
populate a link field 

### ISSUE THREAD

**Issue by ayrat555** [tgel0/crssnt#3]
Hello.

I'm not using your project but I found a feed generated by it in [my RSS reader bot](https://github.com/ayrat555/el_monitorro).

Is it possible to populate a link field for RSS items? currently, only the title contains a link.

Otherwise, users are not able to receive updates

**Comment by tgel0** [comment]
Hello, item link fields will only be populated if the source Sheet contains links as well.

See [here](https://www.notion.so/tgel0/Start-here-crssnt-101-how-to-get-started-043e0a6913a84fea8165e4fe83659258) for more details.
