### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by amblerkr** [tgel0/crssnt#5]
![image](https://user-images.githubusercontent.com/67187038/196868742-298f9166-8ee3-498e-b209-45e9a44a5e97.png)
The feed caused a problem and did not work. I looked into this problem.

>You have unescaped ampersands `&` in your URL. They either need to be (a) changed to character entities `&amp;`, or (b) enclosed in a CDATA section.
>
>A CDATA section lets you leave special characters like & unescaped, so that'd be easiest:

https://stackoverflow.com/questions/3431280/validation-failed-entityref-expecting

`&` was causing trouble.
I changed all `&` to `&amp;` in the `link`
The feed is starting to work.

Google Sheet
Press the shortcut `Ctrl+H`
If you change all `&` to `&amp;`, it will work fine.

**Comment by tgel0** [comment]
Hey @amblerkr,

thank you for posting this!

I actually noticed the same on some of my feeds as well.

When I tried your solution with the `&amp;` replacement the feed itself was working fine but the links were broken. Did you noticed this as well?

My assumption is that I need to properly encode the whole URL, e.g. also the `?` and other special characters. 
I'll look into this some more and try to come up with a good solution for handling the URL encoding from crssnt side.

**Comment by tgel0** [comment]
Update: I added the CDATA section for links and guids as well. Now this error should not happen anymore  (https://github.com/tgel0/crssnt/commit/abe526ebaea6cf653938f389518b189a2a5ffa91).

Note: this only applies for the auto mode. If using the `&mode=manual` option you would need to handle it from your side, e.g. by changing the `&`  in the links or similar.

Any feedback would be much appreciated!
